"""add physical node records

Revision ID: 96a535e3bfc8
Revises:
Create Date: 2026-02-04 03:24:32.356726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a535e3bfc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_node_onboard_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sn', sa.String(length=255), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=False),
    sa.Column('rack', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('cpu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gpu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disk', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('ip', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mgmt_ip', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metainfo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ltp_sdk'
    )
    op.create_index('idx_physical_node_onboard_records_category', 'physical_node_onboard_records', ['category'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_onboard_records_hostname', 'physical_node_onboard_records', ['hostname'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_onboard_records_rank', 'physical_node_onboard_records', ['rank'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_onboard_records_sku', 'physical_node_onboard_records', ['sku'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_onboard_records_sn', 'physical_node_onboard_records', ['sn'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_onboard_records_timestamp', 'physical_node_onboard_records', ['timestamp'], unique=False, schema='ltp_sdk')
    op.create_table('physical_node_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('onboard_id', sa.BigInteger(), nullable=False),
    sa.Column('op_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=True),
    sa.Column('metainfo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['onboard_id'], ['ltp_sdk.physical_node_onboard_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ltp_sdk'
    )
    op.create_index('idx_physical_node_actions_onboard_id', 'physical_node_actions', ['onboard_id'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_actions_op_type', 'physical_node_actions', ['op_type'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_actions_ticket_id', 'physical_node_actions', ['ticket_id'], unique=False, schema='ltp_sdk')
    op.create_index('idx_physical_node_actions_timestamp', 'physical_node_actions', ['timestamp'], unique=False, schema='ltp_sdk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_physical_node_actions_timestamp', table_name='physical_node_actions', schema='ltp_sdk')
    op.drop_index('idx_physical_node_actions_ticket_id', table_name='physical_node_actions', schema='ltp_sdk')
    op.drop_index('idx_physical_node_actions_op_type', table_name='physical_node_actions', schema='ltp_sdk')
    op.drop_index('idx_physical_node_actions_onboard_id', table_name='physical_node_actions', schema='ltp_sdk')
    op.drop_table('physical_node_actions', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_timestamp', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_sn', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_sku', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_rank', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_hostname', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_index('idx_physical_node_onboard_records_category', table_name='physical_node_onboard_records', schema='ltp_sdk')
    op.drop_table('physical_node_onboard_records', schema='ltp_sdk')
    # ### end Alembic commands ###
